### ISSUE TITLE
Cannot install Alyn

### ISSUE THREAD

**Issue by Gpwner** [kakul/Alyn#12]
When I install Alyn on ubuntu16.04 via pip3,then I type a  import alyn,I get the following message:
>>> import alyn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/alyn-0.1.1-py3.5.egg/alyn/__init__.py", line 2, in <module>
    
ImportError: No module named 'deskew'

can you help me figure out where is the problem?

**Comment by kakul** [comment]
HI @Gpwner unfortunately Alyn is usable with python2, I'll have to figure out a way to support this for python3 as well.
